name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org/
      - run: npm i -g pnpm @antfu/ni
      - run: nci
      - run: npx conventional-github-releaser -p angular
        continue-on-error: true
        env:
          CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: npm run publish
        env:
          CLIENT_ID: ${{secrets.CHROME_CLIENT_ID}}
          CLIENT_SECRET: ${{secrets.CHROME_CLIENT_SECRET}}
          REFRESH_TOKEN: ${{secrets.CHROME_REFRESH_TOKEN}}
    
